### ISSUE TITLE
Hessian matrix seems wrong 

### ISSUE THREAD

**Issue by longchao343** [IntelVCL/FastGlobalRegistration#13] opened 2018-06-03 13:50 UTC
Hi,should hessian matrix be [[I ,-q^],[-q^,q^*q^]] when we do optimization?Bcz according to bch formula jacobian should be [I,-q^].

**Comment by qianyizh** [comment] 2018-06-05 05:07
I will close this since it is a duplicate of:
https://github.com/IntelVCL/Open3D/issues/380

**Closed by qianyizh** 2018-06-05 05:07 UTC
